### ISSUE TITLE
Add more translations

### ISSUE THREAD

**Issue by eschmar** [eschmar/time-ago-bundle#3]
Right now we have translations for English and Swedish. Would be nice to support more!
Use `Resources/translations/messages.en.yml` as a reference and create a new file `messages.XX.yml` with XX being your locale.

**Comment by Kietzmann** [comment]
[Russian translation](https://github.com/eschmar/time-ago-bundle/pull/12)
[Ukrainian translation](https://github.com/eschmar/time-ago-bundle/pull/13)

**Comment by delaineackerman** [comment]
<a href="https://github.com/eschmar/time-ago-bundle/pull/16" target="_blank"> Vietnamese Translation </a>

**Comment by taufikherjanto** [comment]
[Added Indonesian Translation](https://github.com/eschmar/time-ago-bundle/pull/18)

**Comment by eschmar** [comment]
Thanks a lot for all your contributions! It's truly amazing. Thanks to your inputs, i have now migrated to `transChoice` translation. It allows you to define intervals, in which the translation differs, within one single translation string. [More infos on the syntax here](http://symfony.com/doc/current/translation.html#pluralization).

For example english minutes translation:

```
minutes: '{1} 1 minute ago|]1,Inf[ # minutes ago'
```

If you want to check your language, [here is a good guide](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals) describing the different language groups.

Cheers!

**Comment by halilkaya** [comment]
I'm dealing with Turkish translation!
